---
title: "Mini Project 5: Advantages and Drawbacks of Using p-values"
---

1.	Towards the end of Section 1, the authors say “As ‘statistical significance’ is used less, statistical thinking will be used more.” Elaborate on what you think the authors mean. Give some examples of what you think embodies “statistical thinking.”
I think the authors mean that if we stop relying on statistical significance in the traditional way which is having a p-value lower than a somewhat arbitrary threshold, then we will have to be more thorough in our statistical analysis. Some people today believe that showing a p-value < 0.05 automatically means that they have found an effect when there are many things left to consider. If they instead had to show more evidence of this effect, they would have used more statistical techniques, and I think it could increase the understanding of statistics. Some examples of this kind of statistical thinking could be to show where the test statistic falls on the distribution if the null hypothesis is true, discuss if all assumptions are correct and provide some evidence when possible. For example, plot the data to see if CLT holds if it’s used in the hypothesis test. We would also have to get better at interpreting the p-value as a number instead of a categorical variable. What I mean with this is that instead of saying “strong evidence”, “moderate”, or “no evidence”, we would have to interpret what a 0.02 p-value means. I think this definitely requires more statistical thinking.
2.	Section 2, third paragraph: The authors state “A label of statistical significance adds nothing to what is already conveyed by the value of p; in fact, this dichotomization of p-values makes matters worse.” Elaborate on what you think the authors means.
I really agree with the point that the authors make here and it’s something that I have struggled with understanding since I first took stat 113. I think the thing that best describes what they mean in this paragraph is “As Gelman and Stern (2006) famously observed, the difference between “significant” and “not significant” is not itself statistically significant. “.  For example, if we use a threshold of p < 0.05 and we get a p-value of 0.049 or 0.052, the meaning of these p-values is incredibly similar, and yet if these were two different studies, one of them might have gone unpublished. I even think that these labels for p-values have hurt the scientific community a lot over time as I have read articles about how researchers have manipulated their data to be able to reach a p < 0.05 instead of reporting the p-value they originally would got. This makes replicating results much harder, and it makes the research less credible. If we instead of using labels with hard thresholds just reported the p-value as a number and used statistical thinking as described above, then I think more good research would be published and there would be less bias in what is reported.
3.	Section 2, end of first column: The authors state “For the integrity of scientific publishing and research dissemination, therefore, whether a p-value passes any arbitrary threshold should not be considered at all when deciding which results to present or highlight.” Do you agree or disagree? How should it be decided which results to present/highlight in scientific publishing?

I agree with this. I believe we would get better research if researchers did not choose what to highlight based on a p-value below an arbitrary threshold. If we instead used p-values as the number it is and interpreted it in context of the research, I think it would allow researchers to present more interesting results even if they are not below for example p < 0.05. However, there is of course a problem in that we don’t want research to be published without considering that deviations from the null hypothesis could simply be due to random chance. If researchers highlight results without interpreting p-values carefully, there is a risk of overstating findings that are actually consistent with the null. A better approach would be to present all results transparently, discuss p-values as continuous evidence rather than binary cutoffs. I believe this can lead to more rigorous research and more rigorous control/review before research is published because if we are not dependent on an arbitrary cutoff, then researchers need to provide more evidence to why the effect they have found should be considered. 

4.	Section 3, end of page 2: The authors state “The statistical community has not yet converged on a simple paradigm for the use of statistical inference in scientific research – and in fact it may never do so. A one-size-fits-all approach to statistical inference is an inappropriate expectation.” Do you agree or disagree? Explain.

I think this one is tricky because I agree that different studies and different disciplines might benefit from different approaches to statistical inference. For example, in some fields, making a type 1 error is much more serious than it is in other fields and vice versa. However, if every scientist would use their own technique for statistical inference, this would make it very hard to follow research and to know if a publishing shows an interesting effect or not. I believe that the right way to go is something in between of these two extremes. I think the authors explain it well with their ATOM model and I believe that if everyone followed their guidelines, we would get better research. I think it would be good to have some clearer guidelines for what is expected to show in a study when it comes to statistical inference such as effect sizes, clear interpretations of p-values, discussions of assumptions etc. I think the key word in their sentence is “a simple paradigm”, I don’t think statistical inference will nor should ever be simple. There are so many things to consider and making it “simple” would by definition look away from many of the difficulties and uncertainties related to statistical inference. Instead I think the goal should be to make statistical inference robust and replicable even if it requires more work. 

5.	Section 3.2: The authors note that they are envisioning “a sort of ‘statistical thoughtfulness’.” What do you think “statistical thoughtfulness” means? What are some ways to demonstrate “statistical thoughtfulness” in an analysis?

I think statistical thoughtfulness can mean a lot of things. I really like how they authors discuss the importance of being clear on if a study is exploratory or planned and the difference it makes. If a study is planned, then I agree that the hypothesis need to be clearly stated at the beginning which I think is praxis anyway. However, what I really liked was the minimal meaningful effect size prior to analyzing data. As an economics major, I find cost-benefit and opportunity costs very interesting, and I believe that having a minimal meaningful effect size would make it easier to argue for a certain intervention after a study. If a researcher says that their study will need an effect of at least x% to be worth the cost and risk of implementing it in for example a school, before the study is began, then I believe their results would be much more credible. Like the authors state, I believe there is a high risk that a researcher argues that the effect they found in their data is enough for it to be implemented. Stating a minimal effect size prior to the study makes a researcher think about the costs and benefits associated to what they are studying and I believe this could make a significant (scary word to use here) difference in the effect of research in real life applications. 
I also think statistical thoughtfulness can be demonstrated by understanding your data, discussing your model assumptions and if you believe that are fulfilled, and discuss your model specification. This is necessary for any statistical results to be taken seriously. In Econometrics we experimented with different model specifications to better understand the importance of a correctly specified model and the differences really surprised me. 
The authors also mention the importance of reading and mentioning prior research in the area. I agree that it is important to learn from existing research, to see what we know, and what evidence there is to support those claims. However, when reviewing existing research, I think it’s important to realize that things might have changed since it was published and we need to be critical and thoroughly go through the existing studies and ask ourselves questions such as “do their assumptions still hold?”, and “were their model correctly specified?” etc. I’m surprised that the authors did not mention much about this since they are so critical of a lot of research that is published throughout the paper. 


6.	Section 3.2.4: A few of the authors of papers in this special issue argue that some of the terminology used in statistics, such as “significance” and “confidence” can be misleading, and they propose the use of “compatibility” instead. What you do you think they believe the problem is? Do you agree or disagree (that there is a problem and that changing the name will help)?
I understand what they mean, especially with significance as it stems from an arbitrarily chosen threshold. I can also find confidence somewhat misleading because it kind of implies there is very little uncertainty when there still can be uncertainty. Also, a lot of people think that a 95% confidence interval means that there is a 95% probability that the true value which is not true. I think they believe that the problem is that using these words and approaches simplifies the approach to statistical inference to a point where thoughtfulness is no longer needed.
However, I’m not sure that changing the name of confidence to combability will solve the bigger picture problem. I do agree that combability describes it well, but I believe that even if the name is changed, scientists might still use it in the same way as before. However, interpreting p-values as their number instead of saying significant or not I think would make a bigger change. I also like their idea of testing more than one hypothesis, such as testing it against the predetermined minimal effect size. I think that better statistical education and higher requirements of statistical thoughtfulness during peer review is probably the best approach to moving beyond a world of p < 0.05 and changing names of concepts will not get us there. 

7.	Find a quote or point that really strikes you (i.e., made you think). What is the quote (and tell me where to find it), and why does it stand out to you?
There were many quotes that stood out to me but the general idea that stood out to me the most was to always declare a minimum effect size before collecting and analyzing data and to test more than one null hypothesis. One example where this is mentioned is 3.2.2 paragraph 3
“Despite these limitations, if you present p-values, do so for more than one hypothesized value of your variable of interest (Fraser 2019; Greenland 2019), such as 0 and at least one plausible, relevant alternative, such as the minimum practically important effect size (which should be determined before analyzing the data).”
This makes a lot of sense to me. It has researchers analyze the costs and benefits before conducting their study, it makes the literature review more important since prior research is likely a good place to start for a minimum practically important effect size. I also think it makes sense to look at more than a non-zero effect since a p-value says nothing about how big an effect is, and for research that can be implemented in the real world, effect size matters a lot. I think it can be an important step for planned studies to not slip into the exploratory side since a researcher has not only have to come up with the null hypothesis but also a minimum practically important effect. If this is not done before the study, then I think there is a risk that some researchers would argue for a minimum practically important effect that fits their data instead of doing an unbiased cost and benefit analysis. I think this idea stood out to me because in class we always talk about testing one null and one alternative hypothesis, but this is arguing that we can do more. It also combines the cost/benefit and opportunity cost mindset that is often used in economics with statistics. 
