{
  "hash": "cb2e588b30472b104ea2790017a2f25d",
  "result": {
    "markdown": "---\ntitle: \"Mini Project 4: Bayesian Analysis\"\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n:::\n\n\n\n## Priors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps <- seq(0, 1, length.out = 1000)\n\n## Non-informative Prior\nnon_informative_prior <- dbeta(ps, 1,1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Prior Asssuming 46 out of 66 points on his own serve. The standard error of this estimate is 0.05657.\n\ntarget_mean <- 46 / 66\n\nalphas <- seq(0.1, 150, length.out = 500)\nbetas <- 0.3031 * alphas / 0.6969\n\nparam_df <- tibble(alphas, betas)\nparam_df <- param_df |> \n  mutate(vars = (alphas * betas) / ((alphas+betas)^2 * \n                                          (alphas+betas+1)))\n\n\ntarget_var <- 0.05657^2\n\nparam_df <- param_df |> mutate(dist_to_target = abs(vars - target_var))\n\n\nparam_df |> filter(dist_to_target == min(dist_to_target))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  alphas betas    vars dist_to_target\n   <dbl> <dbl>   <dbl>          <dbl>\n1   45.2  19.6 0.00321     0.00000995\n```\n:::\n\n```{.r .cell-code}\ninformative_prior_one <- dbeta(ps, 45.2, 19.6)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Informative prior assuming who claims that they think Nadal wins about 75% of the points on his serve against Djokovic. They are also “almost sure” that Nadal wins no less than 70% of his points on serve against Djokovic.\n\nalpha <- seq(0.01, 300, length.out = 1000)\nbetas <- 0.25* alpha / 0.75\npossible_params <- tibble(alpha, betas)\npossible_params\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,000 × 2\n   alpha   betas\n   <dbl>   <dbl>\n 1 0.01  0.00333\n 2 0.310 0.103  \n 3 0.611 0.204  \n 4 0.911 0.304  \n 5 1.21  0.404  \n 6 1.51  0.504  \n 7 1.81  0.604  \n 8 2.11  0.704  \n 9 2.41  0.804  \n10 2.71  0.904  \n# ℹ 990 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## want alpha and beta such that pbeta(0.7, alpha, beta) = some small value which is up to us to choose\n## I will choose 0.05 since it said \"almost sure\"\n\npossible_params |> mutate(probs = pbeta(0.7, alpha, betas)) |> \n  mutate(dist_to_target = abs(probs - 0.05)) |>\n  filter(dist_to_target == min(dist_to_target))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  alpha betas  probs dist_to_target\n  <dbl> <dbl>  <dbl>          <dbl>\n1  160.  53.3 0.0500     0.00000982\n```\n:::\n\n```{.r .cell-code}\n## Changing the \"small value\" has a big effect on the paramneters in the prior. You could argue this makes this prior worse or at least harder to get correct. \n\n## When changing the value to 0.02, alpha goes from 160 to 252 and beta from 53.3 to 83.9\n\ninformative_prior_two <- dbeta(ps, 160, 53.3)\n```\n:::\n\n\n## Plot priors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create df with ps and all priors\nprior_plot_df <- tibble(ps, non_informative_prior, informative_prior_one,\n                  informative_prior_two) |>\n  pivot_longer(2:4, names_to = \"distribution\", values_to = \"density\")\n\n# Color by distribtuin, had to rmeove separate because i had different variable names\nggplot(data = prior_plot_df, aes(x = ps, y = density, colour = distribution)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Posteriors\n\nWe know since before that the posterior will follow a beta(alpha + yobs, n - yobs + beta) distribution.\nIn our case, yobs = 56 and n = 84. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnon_informative_posterior <- dbeta(ps, 1 + 56, 84 - 56 +1)\n\ninformative_posterior_one <- dbeta(ps, 45.2 + 56, 84 - 56 + 19.6)\n\ninformative_posterior_two <- dbeta(ps, 160 + 56, 84 - 56 + 53.3)\n```\n:::\n\n\n### Posterior Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_plot_df <- tibble(ps, non_informative_posterior, informative_posterior_one,\n                  informative_posterior_two) |>\n  pivot_longer(2:4, names_to = \"distribution\", values_to = \"density\")\n\n# Color by distribtuin, had to rmeove separate because i had different variable names\nggplot(data = posterior_plot_df, aes(x = ps, y = density, colour = distribution)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Bayes Estimates and Credible Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Non-informative Bayes estimate\n(1+56) / (84 - 56 +1 + 1 + 56)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6627907\n```\n:::\n\n```{.r .cell-code}\n## Informative one Bayes estimate\n(45.2 + 56) /  (84 - 56 + 19.6 + 45.2 + 56)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6801075\n```\n:::\n\n```{.r .cell-code}\n## Informartive two Bayes estimate\n(160 + 56) /  (84 - 56 + 53.3 + 160 + 56)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7265388\n```\n:::\n:::\n\n\nPosterior means:\n\nNon-informative posterior mean: 0.6627907\nInformative posterior mean 1: 0.6801075\nInformative Posterior mean 2: 0.7265388\n\n\n### 90% credible intervals for p \n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Non-informative 90% credible interval for p\nqbeta(c(0.05, 0.95), 57, 29)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5772453 0.7440061\n```\n:::\n\n```{.r .cell-code}\n## Informative one 90% credible interval for p\nqbeta(c(0.05, 0.95), 101.2, 47.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6160421 0.7414111\n```\n:::\n\n```{.r .cell-code}\n## Informative two 90% credible interval for p\nqbeta(c(0.05, 0.95), 216, 81.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6832283 0.7681138\n```\n:::\n:::\n\n\nNon-informative 90% credible interval for p: (0.5772453, 0.7440061)\nInformative 1 90% credible interval for p: (0.6160421, 0.7414111)\nInformative 2 90% credible interval for p: (0.6832283, 0.7681138)\n\n\n\n## Project Report\n\nIn this project we try to model the probability that Nadal wins a point on his serve when playing on a clay surface. I will answer this question by trying a couple different prior distributions that have different assumptions, combine them with the given data, and compare the three different posterior distributions to see which one I think best models the data. \n\ntyped work justifying the decisions you made to create the two informative priors. What did you assume when you made those priors?\n\nFor the first informative prior distribution I assumed that the prior follow a similar distribtuion as the given data so I set the mean of the prior beta distribution to p_hat and solved for beta. I used this information to construct a df with possible alpha and beta combinations. I then used the standard deviation from the data to find the alpha and beta that best fit the data. \n\nFor the second informative prior distribution I used the information given from the sports announcer. I solved for alpha and beta using the target mean. To find the combination of alpha and beta that best fits the sports announcer's guess I solved for the alpha and beta that have as close as possible to 5% chance of the proportion of serves being less than 70%. I chose 5% because of the announcer's wording of being \"almost sure\". I believe any number between 2% and 15% would be a reasonable guess. This is a weakness of bayesian models, the priors can be subjective and different priors can lead to very different results. \n\n#### Priors Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = prior_plot_df, aes(x = ps, y = density, colour = distribution)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### Posteriors Plot\n\nTo obtain my posteriors I used the fact we saw in class that if you have a beta prior and binomial data, the posterior distribution is Beta(alpha_post = alpha_prior + yobs, beta_post = n - yobs + beta_prior)\n\nFrom the data I see that yobs = 56 and that n = 84. I then apply this equation to all three of my priors to obtain the three posteriors. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = posterior_plot_df, aes(x = ps, y = density, colour = distribution)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nI used the alpha and beta for each posterior to calculate the posterior mean in the following way:\nalpha / alpha + beta\n\nPosterior means:\n\nNon-informative posterior mean: 0.6627907\nInformative posterior mean 1: 0.6801075\nInformative Posterior mean 2: 0.7265388\n\nI used the qbeta function to obtain the 90% credible intervals which can be found in the code above. \n\nNon-informative 90% credible interval for p: (0.5772453, 0.7440061)\nInformative 1 90% credible interval for p: (0.6160421, 0.7414111)\nInformative 2 90% credible interval for p: (0.6832283, 0.7681138)\n\nThere is a 90% probability that Nadal wins between 57.7 and 74.4% of the points when he's serving on clay if we use the non_informative prior. The interval is 61.6% to 74.1% if we use data from the past match against Djokovic to construct our prior and 68.3% to 76.8% if we use the sports announcer's estimate and a 5% \"small number\" to construct our prior.  \n\nThe posteriors are different from each other because they have different prior distributions that are assuming different things about Nadal's ability to win points on his serve. I would probably choose the second posterior because I think that it makes the most sense to base thge prior on actual data. However, I would prefer to have more than one data point to base my prior on. The data used might not be representative of Nadal's ability to hold his serve against other players than Djokovic or even agisnt other matches against Djokovic. Even with these caveats I believe it's the best prior because it contains more information than the non_informative prior. The second informative prior could be a good choice but I don't like the subjectivity of choosing a \"almost sure\" number and how big the difference is in alphas and betas based of different \"small numbers\".  \n\nI think the second informative posterior has a lower variance than the other two because we kind of artificially create this low variance by restricting the prior model to have a low probability, in my case 5% that the proportion of points won on serve is less than 70%. This will give the prior a low variance which we can also see in the posterior. \n\nIn this project, I found three different bayesian models that try to predict what proportion of points Nadal will win on his serve when playing on clay. By trying three different prior distributions, I can compre my assumptions and the resulting posteriors and choose the model I deem best. We see that the models predict that Nadal will win between 66.3 and 72.6% of the points on his serve. ",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}