---
title: "Mini Project 2: A Meaningful Story"
---
Growing up on a horse farm in Sweden I have always been used to being around animals. I helped my mom walk the horses, fill up water, measure up food, keep equipment clean, and much more. But I was never a big fan of horses myself, I thought they took too much time to take care of and that they didn’t give you much back. This could also be because my dad is terrified of horses and tried his best to get me and my brother interested in racket sports, soccer, and motor vehicles like our tractor, atv, and dirt bikes. His tactic worked and we never became horse riders. However, we were still animal lovers and wanted our own animals. We had many discussions on what we should get. Sheep? No, they smell bad and the likelihood of them running away and causing problems is too high. Cows? Too much work. Pigs? Not that cute. Although I did want a mini pig for a while, I failed to convince my parents. We ended up getting chickens. We got mini-cochins, small chicken with feathers on their feet.

Chicken don’t require too much work, they need clean water, eat all your leftovers, and they give you eggs back as a reward. It was the perfect animal for my brother and I to take care of. We ended up getting 12 chickens and one rooster. They became very tame as my brother and I would pet them a lot and once they grew up, they started producing a lot of eggs.

We soon understood that we had to eat a lot of eggs because they were some very well producing chickens. We had to try and estimate the random variable of how many eggs 12 chicken produce in a day. This required some training and there were many parameters in play such as the season of the year, what food we gave them, and the cycle they are in. This was harder than we first thought. After observing them for a year, taking random samples and writing them down, we noticed that the number of eggs collected each day seemed to vary randomly between 0 and approximately 0.9n, with no particular number occurring more frequently than another. Since there was no clear central tendency and each value within that range appeared equally likely over time, we assumed the number of eggs per day followed a uniform distribution with theta1=0 and an estimator for theta2​. Our estimator for theta2 was 0.9n because we had never measured one egg per chicken for one day. This produced an estimate of a uniform distribution with an expected value of 5.4 eggs per day.

Unfortunately, some days we got zero eggs, and they could even go weeks with zero eggs. But sometimes we would get over 70 eggs a week. Needless to say, the variance was very high, and it was hard to figure out why. We began to wonder—was our estimator biased? Were we systematically over or underestimating production because we ignored extreme fluctuations? Despite the high variance, our estimator was at least consistent as over long periods, it stabilized around the average number of eggs we collected.

Like all good stories this one also ends in tragedy. Our chickens were roaming free on the farm and in our garden every day. They went into their hut before dusk, and we closed their hatch so no predators could get in. One dark October night, a small, nasty ferret had sneaked through the chicken wire. The morning after we had no chicken left. It was a total devastation for all of us. We had accounted for foxes in our risk assessment but had failed to consider the likelihood of a ferret attack. Our estimation had been incomplete, and we had underestimated the probability of total loss. After that both my brother and I were done raising chicken and we didn’t get new ones again.

However, only a year ago my dad picked it up again and got 6 new chickens that again roam the farm, and the garden, and in a year hopefully will produce eggs. Maybe he will be able to derive a better estimator than we were. After all, we were only 12 and 8 years old trying to derive a maximum likelihood function, maybe not with weird symbols and logs, but with the eggs we collected every day.
